version: "2"
services:
  bugs:
    build:
      context: .
      dockerfile: bugs/Dockerfile
    restart: always
    volumes:
    - .:/go/src/garlic
    container_name: bugs
    ports:
    - 8801:8081
  notificator:
    build:
      context: .
      dockerfile: notificator/Dockerfile
    restart: always
    volumes:
    - .:/go/src/garlic
    container_name: notificator
    ports:
    - 8802:8082
  users:
    build:
      context: .
      dockerfile: users/Dockerfile
    restart: always
    volumes:
    - .:/go/src/garlic
    container_name: users
    ports:
    - 8800:8081
