apiVersion: apps/v1
kind: Deployment
metadata:
  name: bug-deployment
  labels:
    app: bug
spec:
  selector:
    matchLabels:
      app: bug
  replicas: 1
  template:
    metadata:
      labels:
        app: bug
    spec:
      containers:
        - name: bug
          image: yefriddavid/garlic-bugs:v1
          ports:
            - name: bug-service
              containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: bug-service
spec:
  selector:
    app: bug
  ports:
    - port: 8081
      targetPort: user-service