apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificator-deployment
  labels:
    app: notificator
spec:
  selector:
    matchLabels:
      app: notificator
  replicas: 1
  template:
    metadata:
      labels:
        app: notificator
    spec:
      containers:
        - name: notificator
          image: yefriddavid/notificator-garlic:v1
          ports:
            - name: notificator-service
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: notificator-service
spec:
  selector:
    app: notificator
  ports:
    - port: 3000
      targetPort: notificator-service