apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: yefriddavid/garlic-users:v1
          imagePullPolicy: "Always"
          ports:
            - name: user-service
              containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - name: http
      port: 8081
      nodePort: 30090
  type: NodePort